title: AddCombi
description: Additive combinatorics in Lean
baseurl: ""
url: "https://yaeldillies.github.io/add-combi/"
github_username: YaelDillies
repository: YaelDillies/add-combi

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
