name: Build Lean project

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  style_lint:
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - name: Check for long lines
        if: always()
        run: |
          ! (find AddCombi -name "*.lean" -type f -exec grep -E -H -n '^.{101,}$' {} \; | grep -v -E 'https?://')

      - name: Don't 'import Mathlib', use precise imports
        if: always()
        run: |
          ! (find AddCombi -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Mathlib$')


  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Copy README.md to website/index.md
        run: cp README.md website/index.md

      - name: Check AddCombi.Mathlib only imports from Mathlib or AddCombi.Mathlib
        run: python3 scripts/check_mathlib_imports.py

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.0.0

      - name: Get cache
        run: ~/.elan/bin/lake exe cache get || true

      - name: Build project
        run: ~/.elan/bin/lake build AddCombi

      - name: Build import graph
        run: |
          sudo apt-get update
          sudo apt install graphviz -y
          ~/.elan/bin/lake exe graph website/import_graph.pdf

      - name: Cache dependencies docs
        uses: actions/cache@v3
        with:
          path: docbuild/.lake/build/doc
          key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            MathlibDoc-

      - name: Build documentation
        run: scripts/build_doc.sh

      - name: Move documentation to the website
        run: |
          mkdir -p website/docs
          mv docs/build website/docs

      - name: Bundle website dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: website
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle website
        working-directory: website
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload docs & blueprint artifact to website
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/_site

      - name: Deploy website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
